added configuration file to either use postgres as DBMS or mysql fixed readme fixed default config files

diff --git a/files/atlassian-backup b/files/atlassian-backup
--- a/files/atlassian-backup
+++ b/files/atlassian-backup
@@ -9,7 +9,12 @@ if [ "x${1}" = "x" ]; then
 fi
 
 if [ -e ${CONFIG_FILE} ]; then
-    source ${CONFIG_FILE}
+    if source ${CONFIG_FILE}; then
+        echo "Read config file succeeded!"
+    else
+        echo "Error: ${CONFIG_FILE} could not be sourced."
+        exit 1
+    fi
 else
     echo "Error: ${CONFIG_FILE} missing"
     exit 1
@@ -33,8 +38,29 @@ function backup_attachments() {
 }
 
 function dump_database() {
-    echo "Dumping ${APP} database"
-    /usr/bin/pg_dump -U "${DB_USER}" "${DB_NAME}" -h "${DB_HOST}" > "${DATABASE_DUMP_OUTPUT}"
+    echo "Trying to dump ${APP} database using DBMS ${DB_DBMS}"
+    case "$DB_DBMS" in
+    'mysql')
+        /usr/bin/mysqldump --add-drop-database --host="${DB_HOST}" --user="${DB_USER}" --password="${DB_PASS}" "${DB_NAME}" > "${DATABASE_DUMP_OUTPUT}"
+        cmdSuccess=$?
+        if [ $cmdSuccess -ne 0 ]; then
+            echo "Coudldnt save database. Errorcode: ${cmdSuccess}"
+            exit 1
+        fi
+        ;;
+    'postgres')
+        /usr/bin/pg_dump -U "${DB_USER}" "${DB_NAME}" -h "${DB_HOST}" > "${DATABASE_DUMP_OUTPUT}"
+        cmdSuccess=$?
+        if [ $cmdSuccess -ne 0 ]; then
+            echo "Coudldnt save database. Errorcode: ${cmdSuccess}"
+            exit 1
+        fi
+        ;;
+    *)
+        echo "Invalid DBMS! Database CANNOT be saved! Check config file ${CONFIG_FILE}."
+        exit 1
+        ;;
+    esac
     echo "Created ${DATABASE_DUMP_OUTPUT}"
 }
 
